# Generated by Django 4.2.16 on 2025-09-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetransaction',
            name='bank_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_safe_transactions', to='api.bankdeposit'),
        ),
        migrations.AddField(
            model_name='safetransaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_safe_transactions', to='api.expense'),
        ),
    ]
