# Generated by Django 4.2.16 on 2025-09-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_safetransaction_bank_deposit_safetransaction_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
