# Generated by Django 4.2.16 on 2025-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_frameimage_image_orderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
