# Generated by Django 4.2.16 on 2025-09-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderpayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
