# Generated by Django 4.2.16 on 2025-09-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderpayment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
