# Generated by Django 4.2.16 on 2025-07-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense_is_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherincome',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
