# Generated by Django 4.2.16 on 2025-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_otherincome_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpayment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
