# Generated by Django 4.2.16 on 2025-10-03 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_channelpayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='order_refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_refunds', to='api.order'),
        ),
    ]
