# Generated by Django 4.2.16 on 2025-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expense_order_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
