# Generated by Django 4.2.16 on 2025-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_channelpayment_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Unavailable', 'Unavailable'), ('DOCTOR', 'Docotr')], default='Available', max_length=20),
        ),
    ]
