# Generated by Django 4.2.16 on 2024-12-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.brand')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.code')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.color')),
            ],
        ),
    ]
