# Generated by Django 4.2.16 on 2025-07-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'branch', 'date', 'start_time', 'status')},
        ),
    ]
