# Generated by Django 4.2.16 on 2025-10-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_total_payment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'branch', 'date', 'start_time', 'status')},
        ),
    ]
