# Generated by Django 4.2.16 on 2025-07-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Unavailable', 'Unavailable'), ('DOCTOR', 'Doctor')], default='Available', max_length=20),
        ),
    ]
