# Generated by Django 4.2.16 on 2025-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('factory', 'Factory Invoice'), ('manual', 'Manual Invoice'), ('normal', 'Normal Invoice')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'branch', 'date', 'start_time')},
        ),
    ]
