# Generated by Django 4.2.16 on 2025-10-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
