# Generated by Django 4.2.16 on 2024-12-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_coating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='api.coating')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='api.lensetype')),
            ],
        ),
    ]
