# Generated by Django 4.2.16 on 2025-07-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'branch', 'date', 'start_time', 'status')},
        ),
    ]
