# Generated by Django 4.2.16 on 2025-12-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='co_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='co_order',
            field=models.BooleanField(default=False),
        ),
    ]
