# Generated by Django 4.2.16 on 2025-07-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externallens',
            unique_together={('lens_type', 'coating', 'brand')},
        ),
    ]
