# Generated by Django 4.2.16 on 2026-01-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment_arrival_time_appointment_is_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
