# Generated by Django 4.2.16 on 2024-12-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lensstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
            ],
        ),
    ]
