# Generated by Django 4.2.16 on 2025-08-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_orderitem_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBranchChannelFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_branch_channel_fees', to='api.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_branch_channel_fees', to='api.doctor')),
            ],
        ),
    ]
