# Generated by Django 4.2.16 on 2026-01-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_patient_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthday_reminders', to='api.branch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_reminders', to='api.patient')),
            ],
        ),
    ]
