# Generated by Django 4.2.16 on 2024-12-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_powers', to='api.lens')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_powers', to='api.power')),
            ],
        ),
    ]
