# Generated by Django 4.2.16 on 2026-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_birthdayreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayreminder',
            name='is_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='birthdayreminder',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
