# Generated by Django 4.2.16 on 2025-08-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_doctorbranchchannelfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
