# Generated by Django 4.2.16 on 2026-01-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_birthdayreminder_is_sms_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='paid_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payments', to='api.branch'),
        ),
    ]
