# Generated by Django 4.2.16 on 2024-12-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_lenscleaner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensCleanerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_count', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('lens_cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.lenscleaner')),
            ],
        ),
    ]
