# Generated by Django 4.2.16 on 2025-08-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_appointment_branch_fees_appointment_doctor_fees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorbranchchannelfees',
            unique_together={('doctor', 'branch')},
        ),
    ]
