# Generated by Django 4.2.16 on 2026-02-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_orderpayment_paid_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_pro',
            field=models.BooleanField(default=False),
        ),
    ]
