# Generated by Django 4.2.16 on 2025-08-03 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_orderfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
