# Generated by Django 4.2.16 on 2026-04-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_smstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('birthday', 'Birthday'), ('issue_to_customer', 'Issue to Customer'), ('received_from_factory', 'Received from Factory'), ('order_create', 'Order Create')], max_length=30)),
                ('template', models.TextField()),
                ('source_address', models.CharField(blank=True, max_length=11, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
