# Generated by Django 4.2.16 on 2025-08-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_orderfeedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='initial_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_frames', to='api.branch'),
        ),
        migrations.AddField(
            model_name='lens',
            name='initial_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_lense', to='api.branch'),
        ),
    ]
