# Generated by Django 4.2.16 on 2024-12-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.refraction'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpayment_set', to='api.order'),
        ),
    ]
