# Generated by Django 4.2.16 on 2026-04-17 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_branch_address_branch_contact_one_branch_contact_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('source_address', models.CharField(blank=True, max_length=11, null=True)),
                ('template_type', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], default='error', max_length=10)),
                ('campaign_id', models.BigIntegerField(blank=True, null=True)),
                ('campaign_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('wallet_balance', models.CharField(blank=True, max_length=20, null=True)),
                ('duplicates_removed', models.IntegerField(default=0)),
                ('invalid_numbers', models.IntegerField(default=0)),
                ('mask_blocked_numbers', models.IntegerField(default=0)),
                ('err_code', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.smstemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
