# Generated by Django 4.2.16 on 2025-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='channel_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
