# Generated by Django 4.2.16 on 2025-01-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_lensstock_created_at_lensstock_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='api.brand'),
            preserve_default=False,
        ),
    ]
