# Generated by Django 4.2.16 on 2025-01-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_refractiondetails_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='refractiondetails',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refraction_details', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='refraction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.refraction'),
        ),
    ]
