# Generated by Django 4.2.16 on 2025-01-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_refractiondetails_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sales_staff_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
