# Generated by Django 4.2.16 on 2025-01-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_orderitem_remark_orderitem_sales_staff_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sales_staff_code',
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_staff_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
