# Generated by Django 4.2.16 on 2025-02-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_order_sales_staff_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nic',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
