# Generated by Django 4.2.16 on 2025-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='side',
        ),
        migrations.AlterField(
            model_name='lenspower',
            name='side',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, null=True),
        ),
    ]
