# Generated by Django 4.2.16 on 2025-02-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='refraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='api.refraction'),
        ),
    ]
