# Generated by Django 4.2.16 on 2025-03-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_lenscleaner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='refraction',
            name='nic',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
