# Generated by Django 4.2.16 on 2025-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_refraction_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='refractiondetails',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
