# Generated by Django 4.2.16 on 2025-03-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='refraction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refractions', to='api.patient'),
        ),
    ]
