# Generated by Django 4.2.16 on 2025-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_refraction_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_non_stock',
            field=models.BooleanField(default=False),
        ),
    ]
