# Generated by Django 4.2.16 on 2025-03-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_orderitem_is_non_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lenses', to='api.brand')),
                ('coating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lenses', to='api.coating')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lenses', to='api.order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lenses', to='api.lensetype')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLensPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, null=True)),
                ('external_lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lens_powers', to='api.externallens')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lens_powers', to='api.power')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='external_lens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.externallens'),
        ),
    ]
