# Generated by Django 4.2.16 on 2025-03-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_externallens_externallenspower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallens',
            name='order',
        ),
    ]
