# Generated by Django 4.2.16 on 2025-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_externallens_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='refractiondetails',
            name='h',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='refractiondetails',
            name='pd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='refractiondetails',
            name='shuger',
            field=models.BooleanField(default=False),
        ),
    ]
