# Generated by Django 4.2.16 on 2025-03-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_otheritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_count', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('other_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.otheritem')),
            ],
        ),
    ]
