# Generated by Django 4.2.16 on 2025-03-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_userbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
