# Generated by Django 4.2.16 on 2025-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_customuser_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
