# Generated by Django 4.2.16 on 2025-03-21 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_framestock_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheritemstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_item_stocks', to='api.branch'),
        ),
    ]
