# Generated by Django 4.2.16 on 2025-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_lensstock_branch'),
        ('api', '0061_otheritemstock_branch'),
    ]

    operations = [
    ]
