# Generated by Django 4.2.16 on 2025-03-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_20250323_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refractiondetails',
            name='h',
        ),
        migrations.RemoveField(
            model_name='refractiondetails',
            name='pd',
        ),
        migrations.RemoveField(
            model_name='refractiondetails',
            name='remark',
        ),
        migrations.AddField(
            model_name='refractiondetails',
            name='prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refractiondetails',
            name='refraction_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
