# Generated by Django 4.2.16 on 2025-03-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_20250323_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscleanerstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lens_cleaner_stocks', to='api.branch'),
        ),
    ]
