# Generated by Django 4.2.16 on 2025-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_refractiondetails_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
