# Generated by Django 4.2.16 on 2025-03-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_externallens_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheritemstock',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
