# Generated by Django 4.2.16 on 2025-03-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_lenscleanerstock_branch'),
        ('api', '0066_otheritemstock_limit'),
    ]

    operations = [
    ]
