# Generated by Django 4.2.16 on 2025-03-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_merge_20250327_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='refraction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refractions', to='api.branch'),
        ),
    ]
