# Generated by Django 4.2.16 on 2025-03-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_refraction_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refraction',
            name='refraction_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
