# Generated by Django 4.2.16 on 2025-03-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_merge_20250327_1703'),
        ('api', '0069_alter_refraction_refraction_number'),
    ]

    operations = [
    ]
