# Generated by Django 4.2.16 on 2025-03-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_merge_20250327_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='refractiondetails',
            name='cataract',
            field=models.BooleanField(default=False),
        ),
    ]
