# Generated by Django 4.2.16 on 2025-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_refractiondetails_cataract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='remark',
            new_name='order_remark',
        ),
        migrations.AddField(
            model_name='order',
            name='fitting_on_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='left_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='left_pd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='right_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='right_pd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
