# Generated by Django 4.2.16 on 2025-03-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_order_branch'),
        ('api', '0072_rename_remark_order_order_remark_and_more'),
    ]

    operations = [
    ]
