# Generated by Django 4.2.16 on 2025-03-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_merge_20250329_1255'),
        ('api', '0073_merge_20250329_1823'),
    ]

    operations = [
    ]
