# Generated by Django 4.2.16 on 2025-04-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lens_arrival_status',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('not_received', 'Not Received')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='progress_status',
            field=models.CharField(choices=[('received_from_customer', 'Received from Customer'), ('issue_to_factory', 'Issued to Factory'), ('received_from_factory', 'Received from Factory'), ('issue_to_customer', 'Issued to Customer')], default='received_from_customer', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
