# Generated by Django 4.2.16 on 2025-04-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_invoice_lens_arrival_status_invoice_progress_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='other_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.otheritem'),
        ),
    ]
