# Generated by Django 4.2.16 on 2025-04-02 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_invoice_lens_arrival_status_invoice_progress_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refractiondetails',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
