# Generated by Django 4.2.16 on 2025-04-05 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_refractiondetails_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refractiondetails',
            name='created_by',
        ),
        migrations.AddField(
            model_name='refractiondetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refraction_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
