# Generated by Django 4.2.16 on 2025-04-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_orderitem_other_item'),
        ('api', '0078_remove_refractiondetails_created_by_and_more'),
    ]

    operations = [
    ]
