# Generated by Django 4.2.16 on 2025-04-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpayment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('cash', 'Cash'), ('online_transfer', 'Online Transfer')], max_length=20),
        ),
    ]
