# Generated by Django 4.2.16 on 2025-04-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_expensemaincategory_expensesubcategory_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.AddField(
            model_name='expense',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.expensemaincategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expensesubcategory'),
        ),
    ]
