# Generated by Django 4.2.16 on 2025-04-21 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_expense_created_by_expense_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refraction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
