# Generated by Django 4.2.16 on 2025-04-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_refraction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
