# Generated by Django 4.2.16 on 2025-04-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_bankaccount'),
        ('api', '0087_alter_refraction_created_at'),
    ]

    operations = [
    ]
