# Generated by Django 4.2.16 on 2025-04-23 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_merge_20250423_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallens',
            options={'ordering': ['lens_type', 'coating'], 'verbose_name': 'External Lens', 'verbose_name_plural': 'External Lenses'},
        ),
        migrations.RenameField(
            model_name='externallens',
            old_name='type',
            new_name='lens_type',
        ),
        migrations.RemoveField(
            model_name='externallens',
            name='brand',
        ),
        migrations.AddField(
            model_name='externallens',
            name='branded',
            field=models.CharField(choices=[('branded', 'Branded'), ('non_branded', 'Non-Branded')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externallens',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externallens',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='externallens',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ExternalLensPower',
        ),
    ]
