# Generated by Django 4.2.16 on 2025-04-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_externallens_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallens',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='external_lenses', to='api.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externallens',
            name='lens_factory',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
