# Generated by Django 4.2.16 on 2025-04-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_externallens_brand_externallens_lens_factory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallens',
            name='lens_factory',
        ),
    ]
