# Generated by Django 4.2.16 on 2025-04-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_merge_20250423_1409'),
        ('api', '0091_remove_externallens_lens_factory'),
    ]

    operations = [
    ]
