# Generated by Django 4.2.16 on 2025-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_bankdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='externallens',
            constraint=models.UniqueConstraint(fields=('lens_type', 'coating', 'brand', 'branded'), name='unique_lens_combination'),
        ),
    ]
