# Generated by Django 4.2.16 on 2025-04-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_merge_20250423_2007'),
        ('api', '0094_orderitem_note_externallens_unique_lens_combination'),
    ]

    operations = [
    ]
