# Generated by Django 4.2.16 on 2025-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_orderitem_note_externallens_unique_lens_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
