# Generated by Django 4.2.16 on 2025-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_lens_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
