# Generated by Django 4.2.16 on 2025-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_frame_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
