# Generated by Django 4.2.16 on 2025-04-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_order_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bus System Order', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus System Setting',
                'verbose_name_plural': 'Bus System Settings',
            },
        ),
    ]
