# Generated by Django 4.2.16 on 2025-04-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_merge_20250425_1721'),
        ('api', '0098_bussystemsetting'),
    ]

    operations = [
    ]
