# Generated by Django 4.2.16 on 2025-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_merge_0095_merge_20250425_1721_0098_bussystemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='refractiondetails',
            name='blepharitis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='hb_rx_left_dist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='hb_rx_left_near',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='hb_rx_right_dist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='hb_rx_right_near',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='ntc_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='ntc_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='va_with_glass_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='va_with_glass_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='va_without_glass_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='va_without_glass_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='va_without_ph_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refractiondetails',
            name='va_without_ph_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
