# Generated by Django 4.2.16 on 2025-04-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_refractiondetails_blepharitis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refractiondetails',
            name='prescription',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refractiondetails',
            name='prescription_type',
            field=models.CharField(choices=[('internal', 'Internal Prescription'), ('vision_plus', 'Vision Plus Prescription'), ('other', 'Other Prescription')], default='internal', max_length=20),
        ),
    ]
