# Generated by Django 4.2.16 on 2025-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_remove_refractiondetails_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_frame_only',
            field=models.BooleanField(default=False),
        ),
    ]
