# Generated by Django 4.2.16 on 2025-05-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_externallensbrand_externallenscoating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallens',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
