# Generated by Django 4.2.16 on 2025-05-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_externallens_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussystemsetting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
