# Generated by Django 4.2.16 on 2025-05-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_bussystemsetting_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bussystemsetting',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='bus_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.bussystemsetting'),
        ),
        migrations.AlterField(
            model_name='bussystemsetting',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
