# Generated by Django 4.2.16 on 2025-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_alter_bussystemsetting_options_order_bus_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='brand_type',
            field=models.CharField(choices=[('branded', 'Branded'), ('non_branded', 'Non-Branded')], default='branded', max_length=20),
            preserve_default=False,
        ),
    ]
