# Generated by Django 4.2.16 on 2025-05-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_frame_brand_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('brand', 'brand_type', 'code', 'color', 'species', 'size')},
        ),
    ]
