# Generated by Django 4.2.16 on 2025-05-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_alter_patient_nic_alter_patient_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='invoice_number',
        ),
    ]
