# Generated by Django 4.2.16 on 2025-05-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_safetransaction_safebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_from_safe',
            field=models.BooleanField(default=True),
        ),
    ]
