# Generated by Django 4.2.16 on 2025-05-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_expense_paid_from_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_source',
            field=models.CharField(choices=[('safe', 'Safe'), ('cash', 'Cash'), ('bank', 'Bank')], default='safe', max_length=20),
        ),
    ]
