# Generated by Django 4.2.16 on 2025-05-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_rename_appointment_id_appointment_invoice_number'),
        ('api', '0112_expense_paid_source'),
    ]

    operations = [
    ]
