# Generated by Django 4.2.16 on 2025-05-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_merge_20250507_1939'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_phone_number_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_nic_not_null',
        ),
    ]
