# Generated by Django 4.2.16 on 2025-05-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_remove_patient_unique_phone_number_not_null_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='progress_status',
        ),
        migrations.AddField(
            model_name='order',
            name='progress_status',
            field=models.CharField(choices=[('received_from_customer', 'Received from Customer'), ('issue_to_factory', 'Issued to Factory'), ('received_from_factory', 'Received from Factory'), ('issue_to_customer', 'Issued to Customer')], default='received_from_customer', max_length=30),
        ),
    ]
