# Generated by Django 4.2.16 on 2025-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_remove_invoice_progress_status_order_progress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('received_from_customer', 'Received from Customer'), ('issue_to_factory', 'Issued to Factory'), ('received_from_factory', 'Received from Factory'), ('issue_to_customer', 'Issued to Customer')], default='received_from_customer', max_length=30, null=True),
        ),
    ]
