# Generated by Django 4.2.16 on 2025-05-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_doctorclaiminvoice_doctorclaimchannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='whatsapp_sent',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='whatsapp_sent',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('not_sent', 'Not Sent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorclaimchannel',
            name='invoice_number',
            field=models.CharField(max_length=20),
        ),
    ]
