# Generated by Django 4.2.16 on 2025-05-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_invoice_deleted_at_invoice_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('branch', 'invoice_number')},
        ),
    ]
