# Generated by Django 4.2.16 on 2025-05-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_appointment_note_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refraction',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
