# Generated by Django 4.2.16 on 2025-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_appointment_deleted_at_appointment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
