# Generated by Django 4.2.16 on 2025-05-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_alter_refraction_customer_mobile'),
        ('api', '0123_appointment_is_refund_appointment_refund_note_and_more'),
    ]

    operations = [
    ]
