# Generated by Django 4.2.16 on 2025-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_solderinginvoice_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solderingorder',
            name='progress_status',
            field=models.CharField(choices=[('received_from_customer', 'Received from Customer'), ('issue_to_factory', 'Issued to Factory'), ('received_from_factory', 'Received from Factory'), ('issue_to_customer', 'Issued to Customer')], default='received_from_customer', max_length=30),
        ),
        migrations.AddField(
            model_name='solderingorder',
            name='progress_status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
