# Generated by Django 4.2.16 on 2025-05-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_merge_20250518_1703'),
        ('api', '0126_solderingorder_progress_status_and_more'),
    ]

    operations = [
    ]
