# Generated by Django 4.2.16 on 2025-05-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_order_issued_by_order_issued_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='whatsapp_sent',
        ),
    ]
