# Generated by Django 4.2.16 on 2025-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_remove_orderitem_whatsapp_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
