# Generated by Django 4.2.16 on 2025-05-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_order_fitting_status_and_more'),
        ('api', '0130_order_urgent'),
    ]

    operations = [
    ]
