# Generated by Django 4.2.16 on 2025-05-28 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_merge_20250528_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemwhatsapplog',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitemwhatsapplog',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='api.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fitting_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fitting_ok', 'Fitting Ok'), ('not_fitting', 'Not Fitting'), ('damage', 'Damage')], default='Pending', max_length=20),
        ),
    ]
