# Generated by Django 4.2.16 on 2025-05-28 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_remove_orderitemwhatsapplog_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
