# Generated by Django 4.2.16 on 2025-05-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_alter_order_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
