# Generated by Django 4.2.16 on 2025-05-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_merge_20250526_1229'),
        ('api', '0134_alter_order_issued_date'),
    ]

    operations = [
    ]
