# Generated by Django 4.2.16 on 2025-05-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_merge_20250530_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
