# Generated by Django 4.2.16 on 2025-06-02 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_mntorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_order_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
