# Generated by Django 4.2.16 on 2025-06-03 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_orderpayment_admin_orderpayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
