# Generated by Django 4.2.16 on 2025-06-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_orderitem_admin_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='progress_status',
        ),
        migrations.CreateModel(
            name='OrderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('received_from_customer', 'Received from Customer'), ('issue_to_factory', 'Issued to Factory'), ('received_from_factory', 'Received from Factory'), ('issue_to_customer', 'Issued to Customer')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='api.order')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
