# Generated by Django 4.2.16 on 2025-06-07 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_alter_orderprogress_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefractionDetailsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refraction_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('refraction_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.refractiondetails')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
