# Generated by Django 4.2.16 on 2025-06-10 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_refractiondetailsauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('quantity_changed', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_histories', to='api.branch')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_histories', to='api.frame')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
