# Generated by Django 4.2.16 on 2025-06-10 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_alter_order_height_alter_order_left_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refractiondetailsauditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='refractiondetailsauditlog',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='refractiondetailsauditlog',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='refractiondetailsauditlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refraction_details_audit_logs_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refractiondetailsauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-10 07:39:09.744097'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refractiondetailsauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refraction_details_audit_logs_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
