# Generated by Django 4.2.16 on 2025-06-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_alter_refractiondetailsauditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mntorder',
            name='mnt_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
