# Generated by Django 4.2.16 on 2025-06-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_framestockhistory'),
        ('api', '0146_mntorder_mnt_price'),
    ]

    operations = [
    ]
