# Generated by Django 4.2.16 on 2025-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_merge_0143_framestockhistory_0146_mntorder_mnt_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashInHandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField()),
                ('date', models.DateField()),
                ('cash_in_hand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('before_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('today_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
