# Generated by Django 4.2.16 on 2025-06-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_dailycashinhandrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('external_lense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_status', to='api.externallens')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_status', to='api.order')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
