# Generated by Django 4.2.16 on 2025-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_arrivalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalstatus',
            name='arrival_status',
            field=models.CharField(choices=[('mnt_marked', 'MNT Marked'), ('recived', 'Recived')], default='recived', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitemwhatsapplog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('mnt_marked', 'Mnt Marked')], default='sent', max_length=20),
        ),
    ]
