# Generated by Django 4.2.16 on 2025-06-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_arrivalstatus_arrival_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalstatus',
            name='external_lense',
        ),
    ]
