# Generated by Django 4.2.16 on 2025-06-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_remove_arrivalstatus_external_lense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalstatus',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='arrivalstatus',
            old_name='changed_at',
            new_name='created_at',
        ),
    ]
