# Generated by Django 4.2.16 on 2025-06-19 17:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_alter_arrivalstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lens_arrival_status',
        ),
        migrations.AddField(
            model_name='frame',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalstatus',
            name='arrival_status',
            field=models.CharField(choices=[('mnt_marked', 'Mnt Marked'), ('recived', 'Recived')], default='recived', max_length=30),
        ),
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.frame_image_upload_path),
        ),
    ]
