# Generated by Django 4.2.16 on 2025-06-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_alter_arrivalstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lens_arrival_status',
        ),
        migrations.AlterField(
            model_name='arrivalstatus',
            name='arrival_status',
            field=models.CharField(choices=[('mnt_marked', 'Mnt Marked'), ('recived', 'Recived')], default='recived', max_length=30),
        ),
    ]
