# Generated by Django 4.2.16 on 2025-06-19 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_remove_invoice_lens_arrival_status_frame_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
