# Generated by Django 4.2.16 on 2025-06-23 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_alter_frame_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='framestockhistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='framestockhistory',
            name='performed_by',
        ),
        migrations.AlterField(
            model_name='framestockhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('brand', 'code', 'color')},
        ),
        migrations.CreateModel(
            name='LensStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('quantity_changed', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_stock_histories', to='api.branch')),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_histories', to='api.lens')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_stock_histories', to='api.store')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.store'),
        ),
        migrations.AddField(
            model_name='framestockhistory',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frame_stock_histories', to='api.store'),
        ),
        migrations.AddField(
            model_name='lens',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='api.store'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.store'),
        ),
    ]
