# Generated by Django 4.2.16 on 2025-06-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_store_remove_framestockhistory_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.store'),
        ),
        migrations.AlterField(
            model_name='framestockhistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_stock_histories', to='api.store'),
        ),
        migrations.AlterField(
            model_name='framestockhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='api.store'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.store'),
        ),
    ]
