# Generated by Django 4.2.16 on 2025-06-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_alter_frame_store_alter_framestockhistory_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='store',
        ),
        migrations.RemoveField(
            model_name='framestockhistory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='store',
        ),
        migrations.RemoveField(
            model_name='lensstockhistory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='store',
        ),
        migrations.AddField(
            model_name='frame',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.branch'),
        ),
        migrations.AddField(
            model_name='framestockhistory',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_stock_transfers', to='api.branch'),
        ),
        migrations.AddField(
            model_name='lens',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='api.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensstockhistory',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lens_stock_transfers', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='framestockhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('transfer', 'Transfer'), ('remove', 'Remove')], max_length=10),
        ),
        migrations.AlterField(
            model_name='framestockhistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_frame_stock', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='lensstockhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('transfer', 'Transfer'), ('remove', 'Remove')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lensstockhistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_lens_stock', to='api.branch'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
