# Generated by Django 4.2.16 on 2025-06-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_remove_frame_store_remove_framestockhistory_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='branch',
        ),
        migrations.AlterField(
            model_name='lensstockhistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_stock_histories', to='api.branch'),
        ),
    ]
