# Generated by Django 4.2.16 on 2025-06-27 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_remove_frame_branch_alter_lensstockhistory_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frame_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='frame',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.frameimage'),
        ),
    ]
